import { keyMirror } from "@gilbarbara/helpers";

// import { Status } from "types";

export const ActionTypes = keyMirror({
  GITHUB_GET_REPOS_REQUEST: undefined,
  GITHUB_GET_REPOS_SUCCESS: undefined,
  GITHUB_GET_REPOS_FAILURE: undefined,
  HIDE_ALERT: undefined,
  SHOW_ALERT: undefined,
  SET_APP_OPTIONS: undefined,
  USER_LOGIN_REQUEST: undefined,
  USER_LOGIN_SUCCESS: undefined,
  USER_LOGIN_FAILURE: undefined,
  USER_LOGOUT_REQUEST: undefined,
  USER_LOGOUT_SUCCESS: undefined,
  USER_LOGOUT_FAILURE: undefined,
  GET_USER: undefined,
  GET_USER_SUCCESS: undefined,
  GET_USER_FAILURE: undefined,
  GENERATE_OTP: undefined,
  GENERATE_OTP_SUCCESS: undefined,
  GENERATE_OTP_FAILURE: undefined,
  VERIFY_OTP: undefined,
  VERIFY_OTP_SUCCESS: undefined,
  VERIFY_OTP_FAILURE: undefined,
  UPDATE_USER: undefined,
  UPDATE_USER_SUCCESS: undefined,
  UPDATE_USER_FAILURE: undefined,
  GET_NOTES: undefined,
  GET_NOTES_SUCCESS: undefined,
  GET_NOTES_FAILURE: undefined,
  UPSERT_NOTE: undefined,
  UPSERT_NOTE_SUCCESS: undefined,
  UPSERT_NOTE_FAILURE: undefined,
  CREATE_NEW_NOTE: undefined,
  SELECT_NOTE: undefined,
  SAVE_NOTE_CONTENT: undefined,
  IMPORT_NOTES: undefined,
  ADD_CUSTOM_DOMAIN: undefined,
  ADD_CUSTOM_DOMAIN_SUCCESS: undefined,
  ADD_CUSTOM_DOMAIN_FAILURE: undefined,
  PUBLISH_NOTE: undefined,
  PUBLISH_NOTE_SUCCESS: undefined,
  PUBLISH_NOTE_FAILURE: undefined,
  ARCHIVE_NOTE: undefined,
  ARCHIVE_NOTE_SUCCESS: undefined,
  ARCHIVE_NOTE_FAILURE: undefined,
  DELETE_NOTE: undefined,
  DELETE_NOTE_SUCCESS: undefined,
  DELETE_NOTE_FAILURE: undefined,
  GET_NOTE: undefined,
  GET_NOTE_SUCCESS: undefined,
  GET_NOTE_FAILURE: undefined,
  RESET_USER_STATE: undefined,
  SET_NOTE_SLUG: undefined,
  SET_NOTE_SLUG_SUCCESS: undefined,
  SET_NOTE_SLUG_FAILURE: undefined,
  SEARCH_NOTES: undefined,
  SEARCH_NOTES_SUCCESS: undefined,
  SEARCH_NOTES_FAILURE: undefined,
  GET_LIST: undefined,
  GET_LIST_SUCCESS: undefined,
  GET_LIST_FAILURE: undefined,
  NEW_LIST_NODE: undefined,
  EDIT_LIST_NODE_POS: undefined,
  EDIT_LIST_NODE_CONTENT: undefined,
  UPSERT_LIST_NODE: undefined,
  CHANGE_SELECTED_NODE: undefined,
  BATCH_PUSH_NODES: undefined,
  MAKE_NOTE_PRIVATE: undefined,
  MAKE_NOTE_PRIVATE_SUCCESS: undefined,
  MAKE_NOTE_PRIVATE_FAILURE: undefined,
  GET_MEMORIES: undefined,
  GET_MEMORIES_SUCCESS: undefined,
  GET_MEMORIES_FAILURE: undefined,
  ADD_MEMORY: undefined,
  ADD_MEMORY_SUCCESS: undefined,
  ADD_MEMORY_FAILURE: undefined,
  UPDATE_MEMORY: undefined,
  UPDATE_MEMORY_SUCCESS: undefined,
  UPDATE_MEMORY_FAILURE: undefined,
  DELETE_MEMORY: undefined,
  DELETE_MEMORY_SUCCESS: undefined,
  DELETE_MEMORY_FAILURE: undefined,
});

export const STATUS = {
  IDLE: "idle",
  RUNNING: "running",
  READY: "ready",
  SUCCESS: "success",
  ERROR: "error",
};
